import React from "react";
import { Menu } from "semantic-ui-react";
import Head from "next/head";
import Link from "next/link";

type HeaderProps = {};

export const Header: React.FC<HeaderProps> = ({}) => {
	return (
		<>
			<Head>
				<title>CrowdCoin Typescript</title>
				<meta
					name="description"
					content="Not generated by create next app kekw"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Menu size="massive" borderless>
				<Link href="/">
					<a className="item">CrowdCoin Typescript</a>
				</Link>
				<Menu.Menu position="right">
					<Link href="/campaigns">
						<a className="item">Campaigns</a>
					</Link>
					<Link href="/campaigns/new">
						<a className="item">+</a>
					</Link>
				</Menu.Menu>
			</Menu>
		</>
	);
};
